### ISSUE TITLE
4.2 falsy 객체

### ISSUE THREAD

**Issue by smoonsf** [astomusic/You-Dont-Know-JS#5]
책에서 falsy 객체의 예로 document.all을 설명하면서 이야기하는데 개념에 대한 이해가 잘 안되네요. 조금 더 찾아볼까요?

**Comment by smoonsf** [comment]
이거는 결국 자바스크립트 스펙에서는 다루지 않는 개념이고 오직 **브라우저엔진** 에서만 있는 개념인가 보네요 하핫;;; 세상에... document.all 같이 원칙적으로 javascript 상으로는 true로 변환해야하는데 브라우저 호환 같은 거지같은 이슈 때문에 그냥 false로 변환되게 했나봐요 ㅎㅎ 이런 케이스가 또 있는지 궁금하네요

**Comment by smoonsf** [comment]
https://stackoverflow.com/a/10394873

**Comment by hekkim** [comment]
```
However, in the DOM, there is one exception to this — a DOM object that is falsy. ...
(중략)
The user agent must act as if the ToBoolean() operator in JavaScript converts the object returned for all to the false value.
(후략)
```
요말이 핵심인 거 같네요

**Comment by hekkim** [comment]
https://javascript.info/browser-environment

저도 처음 알았는데 DOM spec은 JavaScript spec과 별게네요
